[tool.poetry]
name = "farsentimiento"
version = "0.1.0"
description = ""
authors = ["michaelhly <michaelhly@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
grpcio-tools = "^1.56.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
