[tool.poetry]
name = "farsentimiento"
version = "0.1.0"
description = ""
authors = ["michaelhly <michaelhly@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9, <3.11"

[tool.poetry.dev-dependencies]
transformers = "^4.31.0"
datasets = "^2.14.3"
numpy = "^1.24.3"
xformers = "^0.0.20"
tensorflow-macos = "^2.13.0"
requests = "^2.31.0"
urllib3 = "1.26.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
